// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkp4K3cOuuKZRlHnGt21RqcIZmArqqejc',
    appId: '1:289474303249:web:a9d13be5e0eafb389768b0',
    messagingSenderId: '289474303249',
    projectId: 'mbll-cb62e',
    authDomain: 'mbll-cb62e.firebaseapp.com',
    storageBucket: 'mbll-cb62e.appspot.com',
    measurementId: 'G-FR7TWXWVC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBog3ve39muxPRvkFXXrvHM0xBT6l9cUhI',
    appId: '1:289474303249:android:c1f11b685bc04c779768b0',
    messagingSenderId: '289474303249',
    projectId: 'mbll-cb62e',
    storageBucket: 'mbll-cb62e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT_428fOBST2xO-6a497Ncx_AnBoCxWMc',
    appId: '1:289474303249:ios:3b2ffeb8945eb71a9768b0',
    messagingSenderId: '289474303249',
    projectId: 'mbll-cb62e',
    storageBucket: 'mbll-cb62e.appspot.com',
    iosClientId: '289474303249-2ovopu60i7k3fsaq23u6ah8h31rf164t.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilAp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT_428fOBST2xO-6a497Ncx_AnBoCxWMc',
    appId: '1:289474303249:ios:3b2ffeb8945eb71a9768b0',
    messagingSenderId: '289474303249',
    projectId: 'mbll-cb62e',
    storageBucket: 'mbll-cb62e.appspot.com',
    iosClientId: '289474303249-2ovopu60i7k3fsaq23u6ah8h31rf164t.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilAp',
  );
}
